# Generated by Django 3.0.1 on 2020-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191224_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latestTitle', models.CharField(max_length=100, verbose_name='Başlık')),
                ('LatestContent', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
