# Generated by Django 3.0.5 on 2020-05-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200129_1242'),
    ]