# Generated by Django 3.0.3 on 2020-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200129_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestpost',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
