# Generated by Django 3.0.5 on 2020-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestpost',
            name='LatestImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
