# Generated by Django 3.0.5 on 2020-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_latestpost_latestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='LatestImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
