# Generated by Django 3.0.5 on 2020-05-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200504_1134'),
        ('news', '0005_auto_20200224_1850'),
    ]

    operations = [
    ]
