# Generated by Django 3.0.5 on 2020-05-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20200508_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestpost',
            name='image',
        ),
    ]
