# Generated by Django 3.0.5 on 2020-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200508_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=20, verbose_name='Menü Adı')),
                ('menu1', models.CharField(max_length=20, verbose_name='Menü 1')),
                ('menu2', models.CharField(max_length=20, verbose_name='Menü 2')),
                ('menu3', models.CharField(max_length=20, verbose_name='Menü 3')),
                ('menu4', models.CharField(max_length=20, verbose_name='Menü 4')),
            ],
        ),
    ]
