# Generated by Django 3.0.5 on 2020-05-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_homemenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeMenu',
        ),
    ]
