# Generated by Django 3.0.5 on 2020-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200514_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestpost',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Yayınla'),
        ),
    ]
