# Generated by Django 3.0 on 2019-12-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesajınız')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
