# Generated by Django 3.0 on 2019-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-Posta Adresiniz'),
            preserve_default=False,
        ),
    ]
