# Generated by Django 3.0.5 on 2020-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('Adres', models.TextField(verbose_name='Adres')),
                ('eposta', models.EmailField(max_length=254, verbose_name='Epostanız')),
            ],
        ),
    ]
