# Generated by Django 3.0.5 on 2020-05-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpage_adrestitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
