# Generated by Django 3.0.5 on 2020-05-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
