# Generated by Django 3.0.5 on 2020-05-20 23:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='BlogContent',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
