# Generated by Django 3.0.5 on 2020-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200521_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='BlogContent',
            field=models.TextField(verbose_name='İçerik'),
        ),
    ]
