# Generated by Django 3.0.5 on 2020-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200526_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='BlogImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
