# Generated by Django 3.0.5 on 2020-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='BlogImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
